"""add menu analysis columns to restaurants

Revision ID: 1aa852d76619
Revises: 0c6e41c3261e
Create Date: 2026-02-24 09:55:17.059959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa852d76619'
down_revision: Union[str, None] = '0c6e41c3261e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('tiene_embutidos', sa.Boolean(), nullable=True))
    op.add_column('restaurants', sa.Column('productos_detectados', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('menu_analizado_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'menu_analizado_at')
    op.drop_column('restaurants', 'productos_detectados')
    op.drop_column('restaurants', 'tiene_embutidos')
    # ### end Alembic commands ###
