"""Initial migration with all tables

Revision ID: 762c945ad421
Revises: 
Create Date: 2026-02-06 00:36:36.405318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762c945ad421'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_run_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('optimal_k', sa.Integer(), nullable=False),
    sa.Column('silhouette_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('davies_bouldin_index', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('calinski_harabasz_index', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_restaurants_scored', sa.Integer(), nullable=False),
    sa.Column('icp_clients_count', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('num_resenas', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('precio', sa.String(length=10), nullable=True),
    sa.Column('tipo_cocina', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('servicios', sa.Text(), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('nuevo', 'contactado', 'interesado', 'cliente', 'no_interesado')", name='ck_restaurants_status'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_restaurants_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_restaurants_fuente', 'restaurants', ['fuente'], unique=False)
    op.create_index('ix_restaurants_nombre_fuente', 'restaurants', ['nombre', 'fuente'], unique=False)
    op.create_index('ix_restaurants_rating', 'restaurants', ['rating'], unique=False)
    op.create_index('ix_restaurants_status', 'restaurants', ['status'], unique=False)
    op.create_index('ix_restaurants_zona', 'restaurants', ['zona'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('superadmin', 'admin', 'analista', 'viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurant_ml_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.String(length=100), nullable=True),
    sa.Column('icp_similarity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cluster_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('restaurant_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cuisine_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rating_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reviews_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('zone_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('completeness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('restaurant_status_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('records_total', sa.Integer(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_imports')
    op.drop_table('restaurant_status_changes')
    op.drop_table('restaurant_scores')
    op.drop_table('restaurant_notes')
    op.drop_table('restaurant_ml_scores')
    op.drop_table('users')
    op.drop_index('ix_restaurants_zona', table_name='restaurants')
    op.drop_index('ix_restaurants_status', table_name='restaurants')
    op.drop_index('ix_restaurants_rating', table_name='restaurants')
    op.drop_index('ix_restaurants_nombre_fuente', table_name='restaurants')
    op.drop_index('ix_restaurants_fuente', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_table('ml_run_metadata')
    # ### end Alembic commands ###
